[build]
  command = "npm ci && node ./node_modules/vite/bin/vite.js build"
  publish = "dist"
  base = "/"

[build.environment]
  NODE_VERSION = "18"

[context.production]
  environment = { NODE_ENV = "production" }

[context.staging]
  command = "npm ci && node ./node_modules/vite/bin/vite.js build --mode staging"
  environment = { NODE_ENV = "staging" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
