[build]
  command = "npm ci && npm install vite@5.0.8 && npx vite build"
  publish = "dist"
  base = "/"

[build.environment]
  NODE_VERSION = "18"

[context.production]
  environment = { NODE_ENV = "production" }

[context.staging]
  command = "npm ci && npm install vite@5.0.8 && npx vite build --mode staging"
  environment = { NODE_ENV = "staging" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
