[build]
  command = "npm ci && npm run build"
  publish = "dist"
  base = "/"

[context.production]
  environment = { NODE_ENV = "production" }

[context.staging]
  command = "npm ci && npm run build:staging"
  environment = { NODE_ENV = "staging" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
